name: 'Knight Custom Electronics '
favicon: null
layout_spectrum: 0.9267050835769624
typography_spectrum: 0.40642881649546325
title: Your Only Local Electronics Experts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9687344504054636
  lightness: 0.12408206053078175
  saturation: 0.23444297537207603
  rhythmicContrast: 0.9158513259608299
purpose: []
