name: 'Knight Custom Electronics LLC '
favicon: null
layout_spectrum: 0.51068
typography_spectrum: 1
title: Knight Custom Electronics LLC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2b3386'
    - '#7278af'
    - '#d0d2e5'
    - '#979bc5'
  brandStrength: 0.9687344504054636
  lightness: 0.75
  saturation: 0.23444297537207603
  rhythmicContrast: 0.5
purpose: []
